services:
  - type: web
    name: vyoora-ocr
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      # Optional: if your backend calls OpenAI, set this in Render dashboard after creating the service
      # - key: OPENAI_API_KEY
      #   sync: false
